Repository obspy/obspy, pull requests merged in 2018-04, with the labels that each got.

#2089 avoid failing doctests on new mpl 2.2
  obspy/imaging/__init__.py
  obspy/imaging/maps.py
  obspy/imaging/tests/images/scan_mult_sampl.png
  obspy/imaging/tests/test_scan.py
  obspy/signal/_sosfilt.py
Labels: ready for review, testing

#2105 reftek: fix reading file with no data in first channel
  CHANGELOG.txt
  obspy/io/reftek/core.py
  obspy/io/reftek/tests/test_core.py
Labels: .io, bug

#2096 Emsc get events
  misc/docs/source/tutorial/advanced_exercise/advanced_exercise_solution_1.py
  misc/docs/source/tutorial/index.rst
Labels: .clients.fdsn

#2104 Allow invalid ids when writing QuakeML files
  CHANGELOG.txt
  obspy/core/event/base.py
  obspy/io/pde/mchedr.py
  obspy/io/quakeml/core.py
  obspy/io/quakeml/tests/data/invalid_id.xml
  obspy/io/quakeml/tests/data/neries_events.xml
  obspy/io/quakeml/tests/test_quakeml.py
Labels: .io.quakeml, enhancement

#2021 nordic: Bug-fix amplitude and wavefile write
  CHANGELOG.txt
  obspy/io/nordic/core.py
  obspy/io/nordic/tests/test_nordic.py
Labels: .io, bug

#2112 Fix Trace.times(type='matplotlib') being slow
  CHANGELOG.txt
  obspy/CONTRIBUTORS.txt
  obspy/core/trace.py
Labels: .core

#2109 Support for SeismicHandler Evt files
  CHANGELOG.txt
  misc/docs/source/packages/obspy.io.sh.rst
  obspy/io/sh/__init__.py
  obspy/io/sh/core.py
  obspy/io/sh/evt.py
  obspy/io/sh/tests/data/local1.evt
  obspy/io/sh/tests/data/local2.evt
  obspy/io/sh/tests/data/tele1.evt
  obspy/io/sh/tests/data/tele2.evt
  obspy/io/sh/tests/test_evt.py
  setup.py
Labels: .io, enhancement

#2118 try to fix appveyor by using pip<10
  appveyor.yml
Labels: CI

#2117 update/improve PPSD tutorial metadata-wise
  misc/docs/source/tutorial/code_snippets/probabilistic_power_spectral_density.rst
Labels: docs

#2016 Ndk bugfix
  obspy/io/ndk/core.py
Labels: .io.ndk, bug

#2113 fix: use preferred order in read_events and read_inventory
  CHANGELOG.txt
  obspy/core/util/base.py
Labels: .core, .core.event, bug
