Repository obspy/obspy, pull requests merged in 2019-10, with the labels that each got.

#2464 testing: mpl backend switch context manager: add close option
  obspy/core/util/misc.py
Labels: testing

#1962 Create response files from Poles and Zeros lists
  CHANGELOG.txt
  obspy/CONTRIBUTORS.txt
  obspy/core/inventory/response.py
  obspy/core/tests/data/RESP.XX.NS306..SHZ.GS13.1.2180
  obspy/core/tests/test_response.py
Labels: .core.inventory

#2463 .flake8 config file, cleanup of flake8 related stuff, and pre-commit hook for flake8
  .circleci/config.yml
  .flake8
  .pre-commit-config.yaml
  misc/docs/source/coding_style.rst
  obspy/core/tests/test_code_formatting.py
Labels: CI, testing

#2475 remove a print statement, fixes #2474
  obspy/signal/spectral_estimation.py
Labels: cleanup

#2476 flake8 config: only set verbose mode in CircleCI
  .circleci/config.yml
  .flake8
Labels: CI, testing

#2400 beachball: try to fix some plotting issues, apparently caused by missing normalization and large numbers
  obspy/imaging/beachball.py
Labels: .imaging

#2405 seedlink client: add option to fetch available stations
  CHANGELOG.txt
  obspy/clients/seedlink/basic_client.py
  obspy/clients/seedlink/client/seedlinkconnection.py
  obspy/clients/seedlink/tests/test_basic_client.py
Labels: .clients.seedlink

#2440 add Stream.stack method
  CHANGELOG.txt
  misc/docs/source/bibliography/Schimmel1997.bib
  obspy/core/stream.py
  obspy/core/tests/test_stream.py
Labels: .core

#2473 Code of conduct
  CODE_OF_CONDUCT.md
Labels: .core, docs, priority: high

#2487 rg16: most tests were not executed
  obspy/io/rg16/tests/test_read_rg16.py
Labels: bug, testing

#2477 basemaps: remove hard coded area_thresh
  CHANGELOG.txt
  obspy/core/tests/images/network_location-basemap2.png
  obspy/imaging/maps.py
Labels: .imaging

#2485 Fix reading rg16 file when start+endtime are inside one data packet
  CHANGELOG.txt
  obspy/io/rg16/core.py
  obspy/io/rg16/tests/test_read_rg16.py
Labels: .io, bug

#2455 PPSD: Add earthquake models from Clinton & Heaton (2002)
  CHANGELOG.txt
  misc/docs/source/bibliography/CauzziClinton2013.bib
  misc/docs/source/bibliography/ClintonHeaton2002.bib
  obspy/CONTRIBUTORS.txt
  obspy/signal/spectral_estimation.py
  obspy/signal/tests/test_spectral_estimation.py
Labels: .signal

#2461 Fix CI
  appveyor.yml
  obspy/core/tests/test_stream.py
  obspy/signal/tests/test_cross_correlation.py
Labels: CI
