Repository obspy/obspy, pull requests merged in 2022-02, with the labels that each got.

#2961 remove basemap definitively
  CHANGELOG.txt
  misc/docs/py3-docs-master.yml
  obspy/core/event/catalog.py
  obspy/core/inventory/inventory.py
  obspy/core/inventory/network.py
  obspy/core/tests/test_event.py
  obspy/core/tests/test_inventory.py
  obspy/core/tests/test_network.py
  obspy/core/util/__init__.py
  obspy/core/util/base.py
  obspy/imaging/maps.py
Labels: ready for review

#2970 add tests with installed cartopy etc and check conda env files used in tests
  .github/docs_conda_env.yml
  .github/test_all_conda_env.yml
  .github/test_conda_env-3.10.yml
  .github/test_conda_env-3.7.yml
  .github/test_conda_env-3.8.yml
  .github/test_conda_env-3.9.yml
  .github/workflows/master_default_tests.yml
  .github/workflows/pull_request.yml
  obspy/conftest.py
Labels: ready for review, test_network

#2758 Faster loadtime
  .github/workflows/master_default_tests.yml
  .github/workflows/pull_request.yml
  CHANGELOG.txt
  obspy/__init__.py
  obspy/core/event/catalog.py
  obspy/core/inventory/response.py
  obspy/core/util/base.py
  obspy/geodetics/base.py
  obspy/imaging/beachball.py
  obspy/imaging/mopad_wrapper.py
  obspy/imaging/source.py
  obspy/io/gse2/libgse2.py
  obspy/io/gse2/paz.py
  obspy/scripts/runtests.py
Labels: ready for review, performance

#2978 filter warnings in spectral estimation test
  obspy/imaging/tests/test_beachball.py
  obspy/signal/tests/test_spectral_estimation.py
Labels: ready for review

#2980 fix more network tests
  obspy/clients/fdsn/mass_downloader/utils.py
  obspy/clients/iris/client.py
  obspy/clients/iris/tests/data/IU.ANMO.00.BHZ.sacpz
  obspy/clients/iris/tests/test_client.py
  obspy/clients/seedlink/tests/test_basic_client.py
Labels: testing, ready for review, test_network

#2943 Adding wheel builder (currently running for every push)
  .github/workflows/build_wheels.yml
  .github/workflows/docs_building.yml
  .github/workflows/release_published.yml
  obspy/core/util/version.py
  setup.py
Labels: release blocker, packaging, ready for review, no_ci

#2991 fix upload of releases
  .github/workflows/build_wheels.yml
Labels: packaging, ready for review, no_ci
