Repository obspy/obspy, pull requests merged in 2023-10, with the labels that each got.

#3352 Added NRCan to known FDSN clients
  CHANGELOG.txt
  obspy/clients/fdsn/__init__.py
  obspy/clients/fdsn/header.py
Labels: ready for review, test_network, build_docs, no_ci

#3362 mpl backend switcher: close figures explicitly
  obspy/core/util/misc.py
Labels: ready for review

#3364 suppress a DeprecationWarning in a dependency
  obspy/conftest.py
Labels: testing, cleanup

#3365 tests: adjust to scipy deprecation warning for moved window functions
  obspy/signal/tests/test_cpxtrace.py
  obspy/signal/tests/test_freqattributes.py
  obspy/signal/tests/test_hoctavbands.py
  obspy/signal/tests/test_polarization.py
Labels: cleanup

#3360 add python 3.12 to github actions
  .github/test_conda_env.yml
  .github/test_mindep_conda_env.yml
  .github/workflows/build_wheels.yml
  .github/workflows/tests.yml
  obspy/signal/tests/test_quality_control.py
Labels: CI
